# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManualControl.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QMainWindow #this is to enable the self.sender function

import globals

from PyQt5.QtCore import QTimer
from datetime import datetime
import database
from relay_lib_seeed import *


class Ui_Control(QMainWindow):
    def setupUi(self, Control):
        Control.setObjectName("Control")
        Control.resize(800, 480)
        Control.setMinimumSize(QtCore.QSize(800, 480))
        self.gridLayout = QtWidgets.QGridLayout(Control)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ControlFrame = QtWidgets.QFrame(Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControlFrame.sizePolicy().hasHeightForWidth())
        self.ControlFrame.setSizePolicy(sizePolicy)
        self.ControlFrame.setObjectName("ControlFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ControlFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Relay1Frame = QtWidgets.QFrame(self.ControlFrame)
        self.Relay1Frame.setObjectName("Relay1Frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Relay1Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblRelay1 = QtWidgets.QLabel(self.Relay1Frame)
        self.lblRelay1.setMinimumSize(QtCore.QSize(90, 69))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblRelay1.setFont(font)
        self.lblRelay1.setObjectName("lblRelay1")
        self.horizontalLayout_2.addWidget(self.lblRelay1)
        self.btnOn1 = QtWidgets.QPushButton(self.Relay1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOn1.sizePolicy().hasHeightForWidth())
        self.btnOn1.setSizePolicy(sizePolicy)
        self.btnOn1.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOn1.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOn1.setObjectName("btnOn1")
        self.horizontalLayout_2.addWidget(self.btnOn1)
        self.btnOFF1 = QtWidgets.QPushButton(self.Relay1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOFF1.sizePolicy().hasHeightForWidth())
        self.btnOFF1.setSizePolicy(sizePolicy)
        self.btnOFF1.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOFF1.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOFF1.setObjectName("btnOFF1")
        self.horizontalLayout_2.addWidget(self.btnOFF1)
        self.verticalLayout.addWidget(self.Relay1Frame)
        self.Relay2Frame = QtWidgets.QFrame(self.ControlFrame)
        self.Relay2Frame.setObjectName("Relay2Frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Relay2Frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblRelay2 = QtWidgets.QLabel(self.Relay2Frame)
        self.lblRelay2.setMinimumSize(QtCore.QSize(90, 69))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblRelay2.setFont(font)
        self.lblRelay2.setObjectName("lblRelay2")
        self.horizontalLayout_4.addWidget(self.lblRelay2)
        self.btnOn2 = QtWidgets.QPushButton(self.Relay2Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOn2.sizePolicy().hasHeightForWidth())
        self.btnOn2.setSizePolicy(sizePolicy)
        self.btnOn2.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOn2.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOn2.setObjectName("btnOn2")
        self.horizontalLayout_4.addWidget(self.btnOn2)
        self.btnOFF2 = QtWidgets.QPushButton(self.Relay2Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOFF2.sizePolicy().hasHeightForWidth())
        self.btnOFF2.setSizePolicy(sizePolicy)
        self.btnOFF2.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOFF2.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOFF2.setObjectName("btnOFF2")
        self.horizontalLayout_4.addWidget(self.btnOFF2)
        self.verticalLayout.addWidget(self.Relay2Frame)
        self.Relay3Frame = QtWidgets.QFrame(self.ControlFrame)
        self.Relay3Frame.setObjectName("Relay3Frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Relay3Frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblRelay3 = QtWidgets.QLabel(self.Relay3Frame)
        self.lblRelay3.setMinimumSize(QtCore.QSize(90, 69))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblRelay3.setFont(font)
        self.lblRelay3.setObjectName("lblRelay3")
        self.horizontalLayout_7.addWidget(self.lblRelay3)
        self.btnOn3 = QtWidgets.QPushButton(self.Relay3Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOn3.sizePolicy().hasHeightForWidth())
        self.btnOn3.setSizePolicy(sizePolicy)
        self.btnOn3.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOn3.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOn3.setObjectName("btnOn3")
        self.horizontalLayout_7.addWidget(self.btnOn3)
        self.btnOFF3 = QtWidgets.QPushButton(self.Relay3Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOFF3.sizePolicy().hasHeightForWidth())
        self.btnOFF3.setSizePolicy(sizePolicy)
        self.btnOFF3.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOFF3.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOFF3.setObjectName("btnOFF3")
        self.horizontalLayout_7.addWidget(self.btnOFF3)
        self.verticalLayout.addWidget(self.Relay3Frame)
        self.Relay4Frame = QtWidgets.QFrame(self.ControlFrame)
        self.Relay4Frame.setObjectName("Relay4Frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Relay4Frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblRelay4 = QtWidgets.QLabel(self.Relay4Frame)
        self.lblRelay4.setMinimumSize(QtCore.QSize(90, 69))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblRelay4.setFont(font)
        self.lblRelay4.setObjectName("lblRelay4")
        self.horizontalLayout_8.addWidget(self.lblRelay4)
        self.btnOn4 = QtWidgets.QPushButton(self.Relay4Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOn4.sizePolicy().hasHeightForWidth())
        self.btnOn4.setSizePolicy(sizePolicy)
        self.btnOn4.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOn4.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOn4.setObjectName("btnOn4")
        self.horizontalLayout_8.addWidget(self.btnOn4)
        self.btnOFF4 = QtWidgets.QPushButton(self.Relay4Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOFF4.sizePolicy().hasHeightForWidth())
        self.btnOFF4.setSizePolicy(sizePolicy)
        self.btnOFF4.setMinimumSize(QtCore.QSize(110, 85))
        self.btnOFF4.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnOFF4.setObjectName("btnOFF4")
        self.horizontalLayout_8.addWidget(self.btnOFF4)
        self.verticalLayout.addWidget(self.Relay4Frame)
        self.verticalLayout_5.addWidget(self.ControlFrame)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.RightMenusFrame = QtWidgets.QFrame(Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightMenusFrame.sizePolicy().hasHeightForWidth())
        self.RightMenusFrame.setSizePolicy(sizePolicy)
        self.RightMenusFrame.setMinimumSize(QtCore.QSize(0, 460))
        self.RightMenusFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.RightMenusFrame.setObjectName("RightMenusFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.RightMenusFrame)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MenusSpacingFrame = QtWidgets.QFrame(self.RightMenusFrame)
        self.MenusSpacingFrame.setMinimumSize(QtCore.QSize(200, 200))
        self.MenusSpacingFrame.setObjectName("MenusSpacingFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.MenusSpacingFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.MenusFrame = QtWidgets.QFrame(self.MenusSpacingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MenusFrame.sizePolicy().hasHeightForWidth())
        self.MenusFrame.setSizePolicy(sizePolicy)
        self.MenusFrame.setMinimumSize(QtCore.QSize(121, 200))
        self.MenusFrame.setObjectName("MenusFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MenusFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnHome = QtWidgets.QPushButton(self.MenusFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome.sizePolicy().hasHeightForWidth())
        self.btnHome.setSizePolicy(sizePolicy)
        self.btnHome.setMinimumSize(QtCore.QSize(0, 0))
        self.btnHome.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnHome.setObjectName("btnHome")
        self.verticalLayout_2.addWidget(self.btnHome)
        self.btnControlCenter = QtWidgets.QPushButton(self.MenusFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnControlCenter.sizePolicy().hasHeightForWidth())
        self.btnControlCenter.setSizePolicy(sizePolicy)
        self.btnControlCenter.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnControlCenter.setObjectName("btnControlCenter")
        self.verticalLayout_2.addWidget(self.btnControlCenter)
        self.btnTemperature_2 = QtWidgets.QPushButton(self.MenusFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTemperature_2.sizePolicy().hasHeightForWidth())
        self.btnTemperature_2.setSizePolicy(sizePolicy)
        self.btnTemperature_2.setMinimumSize(QtCore.QSize(0, 0))
        self.btnTemperature_2.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnTemperature_2.setObjectName("btnTemperature_2")
        self.verticalLayout_2.addWidget(self.btnTemperature_2)
        self.btnHumidity = QtWidgets.QPushButton(self.MenusFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHumidity.sizePolicy().hasHeightForWidth())
        self.btnHumidity.setSizePolicy(sizePolicy)
        self.btnHumidity.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        self.btnHumidity.setObjectName("btnHumidity")
        self.verticalLayout_2.addWidget(self.btnHumidity)
        self.horizontalLayout_5.addWidget(self.MenusFrame)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4.addWidget(self.MenusSpacingFrame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem4)
        self.StatusFrame = QtWidgets.QFrame(self.RightMenusFrame)
        self.StatusFrame.setMinimumSize(QtCore.QSize(202, 231))
        self.StatusFrame.setObjectName("StatusFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.StatusFrame)
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.lblTime = QtWidgets.QLabel(self.StatusFrame)
        self.lblTime.setMinimumSize(QtCore.QSize(200, 21))
        self.lblTime.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lblTime.setStyleSheet("qproperty-alignment:AlignCenter;\n"
"background-color:White;\n"
"color:blue;\n"
"font-size:12px;\n"
"font-weight:bold;")
        self.lblTime.setObjectName("lblTime")
        self.verticalLayout_3.addWidget(self.lblTime)
        self.verticalLayout_4.addWidget(self.StatusFrame)
        self.gridLayout.addWidget(self.RightMenusFrame, 0, 3, 1, 1)

        self.retranslateUi(Control)
        QtCore.QMetaObject.connectSlotsByName(Control)

    def retranslateUi(self, Control):
        _translate = QtCore.QCoreApplication.translate
        Control.setWindowTitle(_translate("Control", "Form"))
        self.lblRelay1.setText(_translate("Control", "Relay 1:"))
        self.btnOn1.setText(_translate("Control", "ON"))
        self.btnOFF1.setText(_translate("Control", "OFF"))
        self.lblRelay2.setText(_translate("Control", "Relay 2:"))
        self.btnOn2.setText(_translate("Control", "ON"))
        self.btnOFF2.setText(_translate("Control", "OFF"))
        self.lblRelay3.setText(_translate("Control", "Relay 3:"))
        self.btnOn3.setText(_translate("Control", "ON"))
        self.btnOFF3.setText(_translate("Control", "OFF"))
        self.lblRelay4.setText(_translate("Control", "Relay 4:"))
        self.btnOn4.setText(_translate("Control", "ON"))
        self.btnOFF4.setText(_translate("Control", "OFF"))
        self.btnHome.setText(_translate("Control", "Home"))
        self.btnControlCenter.setText(_translate("Control", "Control\n"
"Center"))
        self.btnTemperature_2.setText(_translate("Control", "Temperature"))
        self.btnHumidity.setText(_translate("Control", "Humidity"))
        self.lblTime.setText(_translate("Control", "10-10-2019 17:06:21"))
        ###########################################################
        ###########################################################

        self.updateTime()
        self.startTimeUpdateTimer()
        self.btnHome.clicked.connect(self.open_home_screen)
        self.btnTemperature_2.clicked.connect(self.open_temp_screen)
        self.btnHumidity.clicked.connect(self.open_humidity_screen)
        self.btnControlCenter.clicked.connect(self.open_control_screen)

        
        self.btnOn1.clicked.connect(self.on_relay1)
        self.btnOFF1.clicked.connect(self.off_relay1)
        self.btnOn2.clicked.connect(self.on_relay2)
        self.btnOFF2.clicked.connect(self.off_relay2)
        self.btnOn3.clicked.connect(self.on_relay3)
        self.btnOFF3.clicked.connect(self.off_relay3)
        self.btnOn4.clicked.connect(self.on_relay4)
        self.btnOFF4.clicked.connect(self.off_relay4)


    def open_home_screen(self):
        globals.manuel.hide()
        globals.Home.show()

    def open_temp_screen(self):
        globals.manuel.hide()
        globals.temp.show()
    
    def open_humidity_screen(self):
        globals.manuel.hide()
        globals.humidity.show()

    def open_control_screen(self):
        globals.manuel.hide()
        globals.control.show()


    def updateTime(self):
            now = datetime.now()
            # H:M:S - DD/MM/YY
            dt_string = now.strftime("%H:%M:%S %d-%b-%Y")
            self.lblTime.setText(dt_string)

    def startTimeUpdateTimer(self):
        self.timer = QTimer()
        self.timer.timeout.connect(self.updateTime)
        self.timer.start(1000) 

    def on_relay1 (self):
        database.updateDB("UPDATE settings SET manual = 1 , status = 1 WHERE relay_id = 1" )
        self.btnOn1.setStyleSheet("background-color:\'green\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_on(1)

    def off_relay1 (self):
        database.updateDB("UPDATE settings SET manual = 0 , status = 0 WHERE relay_id = 1" )
        self.btnOn1.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_off(1)

    def on_relay2 (self):
        database.updateDB("UPDATE settings SET manual = 1 , status = 1 WHERE relay_id = 2" )
        self.btnOn2.setStyleSheet("background-color:\'green\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_on(2)

    def off_relay2 (self):
        database.updateDB("UPDATE settings SET manual = 0 , status = 0 WHERE relay_id = 2" )
        self.btnOn2.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_off(2)

    def on_relay3 (self):
        database.updateDB("UPDATE settings SET manual = 1 , status = 1 WHERE relay_id = 3" )
        self.btnOn3.setStyleSheet("background-color:\'green\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_on(3)

    def off_relay3 (self):
        database.updateDB("UPDATE settings SET manual = 0 , status = 0 WHERE relay_id = 3" )
        self.btnOn3.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_off(3)

    def on_relay4 (self):
        database.updateDB("UPDATE settings SET manual = 1 , status = 1 WHERE relay_id = 4" )
        self.btnOn4.setStyleSheet("background-color:\'green\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_on(4)

    def off_relay4 (self):
        database.updateDB("UPDATE settings SET manual = 0 , status = 0 WHERE relay_id = 4" )
        self.btnOn4.setStyleSheet("background-color:\'royal blue\';color:\'gold\';border-radius:10px;font-size:16px;")
        relay_off(4)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Control = QtWidgets.QWidget()
    ui = Ui_Control()
    ui.setupUi(Control)
    Control.show()
    sys.exit(app.exec_())
